In [12]:
# import ml libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
%matplotlib inline

In [13]:
# import data
iris = pd.read_csv('iris.csv')
iris.head()
# read csv
iris = pd.read_csv('iris.csv')

In [15]:
# split data for traning and validation
from sklearn.model_selection import train_test_split
X = iris.drop('Species', axis=1)
y = iris['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [16]:
# simplest model to train
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [17]:
# evaluate model
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[13  0  0]
 [ 1 17  2]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       0.93      1.00      0.96        13
Iris-versicolor       1.00      0.85      0.92        20
 Iris-virginica       0.86      1.00      0.92        12

       accuracy                           0.93        45
      macro avg       0.93      0.95      0.93        45
   weighted avg       0.94      0.93      0.93        45



In [ ]:
# improve model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]}
grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)
grid_predictions = grid.predict(X_test)

In [19]:
# evaluate improved model
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))

[[13  0  0]
 [ 0 20  0]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00        20
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [20]:
# save model
import pickle
pickle.dump(grid, open('model.pkl', 'wb'))